services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
      redis:
         condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - autoreviewer
    command: uv run uvicorn src.interfaces.api.app:app --host 0.0.0.0 --port 8000 --reload

  review_worker-1:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - autoreviewer
    command: uv run python -m src.interfaces.cli.worker

  review_worker-2:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - autoreviewer
    command: uv run python -m src.interfaces.cli.worker

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - autoreviewer

  loki:
    image: grafana/loki:3.3.2
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./extra/logging/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    networks:
      - autoreviewer

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./extra/logging/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - autoreviewer

  s3:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - autoreviewer

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./extra/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - TZ=UTC
    networks:
      - autoreviewer
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db
    environment:
      - RI_APP_HOST=0.0.0.0
      - RI_APP_PORT=5540
      - RI_TELEMETRY_DISABLE=true
    networks:
      - autoreviewer
    depends_on:
      - redis

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"
      - "4317:4317"
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - phoenix_data:/mnt/data

volumes:
  postgres_data:
  loki_data:
  grafana_data:
  minio_data:
  redis_data:
  redisinsight_data:
  phoenix_data:

networks:
  autoreviewer:
    driver: bridge