"""criteria_workspace_task_binding

Revision ID: 4283d95c7d1f
Revises: 431f09e6a7cf
Create Date: 2026-04-21 03:06:41.561179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4283d95c7d1f'
down_revision: Union[str, Sequence[str], None] = '431f09e6a7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.add_column('criteria', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key("criteria_workspace_fk", 'criteria', 'workspaces', ['workspace_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key("criteria_task_fk", 'criteria', 'tasks', ['task_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('criteria', 'is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint("criteria_workspace_fk", 'criteria', type_='foreignkey')
    op.drop_constraint("criteria_task_fk", 'criteria', type_='foreignkey')
    op.drop_column('criteria', 'task_id')
    op.drop_column('criteria', 'workspace_id')
    # ### end Alembic commands ###
