"""criteria

Revision ID: a9162cfeba21
Revises: 2bd15d841784
Create Date: 2026-04-27 10:18:41.270626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9162cfeba21'
down_revision: Union[str, Sequence[str], None] = '2bd15d841784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('prompt', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criteria', 'prompt')
    # ### end Alembic commands ###
