"""pipeline_tasks

Revision ID: a1c01bdb5d1e
Revises: c408da00194e
Create Date: 2026-04-14 09:54:28.757241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1c01bdb5d1e'
down_revision: Union[str, Sequence[str], None] = 'c408da00194e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_id', 'step', name='uq_pipeline_tasks_solution_step')
    )
    op.drop_table('solution_artifacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_artifacts',
    sa.Column('solution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_tree', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_doc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], name=op.f('solution_artifacts_solution_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('solution_id', name=op.f('solution_artifacts_pkey'))
    )
    op.drop_table('pipeline_tasks')
    # ### end Alembic commands ###
