"""solution_repo_artifact_path

Revision ID: 2bd15d841784
Revises: 4283d95c7d1f
Create Date: 2026-04-22 03:45:02.410859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd15d841784'
down_revision: Union[str, Sequence[str], None] = '4283d95c7d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('github_repo_link', sa.String(), nullable=True))
    op.add_column('solutions', sa.Column('github_repo_branch', sa.String(), nullable=True))
    op.add_column('solutions', sa.Column('artifact_path', sa.String(), nullable=False, server_default=''))
    op.drop_column('solutions', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('link', sa.String(), nullable=False, server_default=''))
    op.drop_column('solutions', 'artifact_path')
    op.drop_column('solutions', 'github_repo_branch')
    op.drop_column('solutions', 'github_repo_link')
    # ### end Alembic commands ###
