"""criteria_solutions_tasks

Revision ID: c408da00194e
Revises: 6d610430c104
Create Date: 2026-04-09 23:01:06.718207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c408da00194e'
down_revision: Union[str, Sequence[str], None] = '6d610430c104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('stage', sa.Enum('PROJECT_DOC', 'CODEBASE', 'MANUAL', name='criterion_stage'), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('use_exam', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('ZIP', 'GITHUB', name='solution_format'), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CANCELLED', 'ERROR', 'AI_REVIEW', 'WAITING_EXAM', 'EXAMINATION', 'HUMAN_REVIEW', 'REVIEWED', name='solution_status'), nullable=False),
    sa.Column('steps', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('human_grade', sa.Integer(), nullable=True),
    sa.Column('human_feedback', sa.String(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_criteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'criterion_id', name='uq_task_criteria_task_criterion')
    )
    op.create_table('solution_artifacts',
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('project_tree', sa.Text(), nullable=True),
    sa.Column('project_content', sa.Text(), nullable=True),
    sa.Column('project_doc', sa.Text(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('solution_id')
    )
    op.create_table('solution_criteria_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_criterion_id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), server_default='', nullable=False),
    sa.Column('stage', sa.Enum('PROJECT_DOC', 'CODEBASE', 'MANUAL', name='solution_criterion_stage'), nullable=False),
    sa.Column('status', sa.Enum('SUFFICIENT', 'NEEDS_CODE', 'NEEDS_STUDENT', 'NEEDS_MANUAL', 'NOT_APPLICABLE', name='solution_criterion_check_status'), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_criterion_id'], ['task_criteria.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solution_criteria_checks')
    op.drop_table('solution_artifacts')
    op.drop_table('task_criteria')
    op.drop_table('solutions')
    op.drop_table('tasks')
    op.drop_table('criteria')
    op.execute("DROP TYPE IF EXISTS criterion_stage;")
    op.execute("DROP TYPE IF EXISTS solution_format;")
    op.execute("DROP TYPE IF EXISTS solution_status;")
    op.execute("DROP TYPE IF EXISTS solution_criterion_stage;")
    op.execute("DROP TYPE IF EXISTS solution_criterion_check_status;")
    # ### end Alembic commands ###
