"""solution

Revision ID: 180ef8456baa
Revises: a2d9af224e86
Create Date: 2026-05-04 04:26:09.538690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "180ef8456baa"
down_revision: Union[str, Sequence[str], None] = "a2d9af224e86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE solution_status ADD VALUE 'PROJECT_GENERATION'")
    op.execute("ALTER TYPE solution_status ADD VALUE 'VALIDATION_WAITING'")
    op.execute("ALTER TYPE solution_status ADD VALUE 'CRITERIA_GRADING'")

    op.execute("UPDATE solutions SET status = 'ERROR' WHERE status = 'AI_REVIEW'")
    op.execute("UPDATE solutions SET status = 'ERROR' WHERE status = 'WAITING_EXAM'")
    op.execute("UPDATE solutions SET status = 'ERROR' WHERE status = 'EXAMINATION'")

    op.execute("ALTER TYPE solution_status DROP VALUE IF EXISTS 'AI_REVIEW'")
    op.execute("ALTER TYPE solution_status DROP VALUE IF EXISTS 'WAITING_EXAM'")
    op.execute("ALTER TYPE solution_status DROP VALUE IF EXISTS 'EXAMINATION'")

    op.add_column("solutions", sa.Column("label", sa.String(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("solutions", "label")

    op.execute("ALTER TYPE solution_status ADD VALUE 'AI_REVIEW'")
    op.execute("ALTER TYPE solution_status ADD VALUE 'WAITING_EXAM'")
    op.execute("ALTER TYPE solution_status ADD VALUE 'EXAMINATION'")

    op.execute("ALTER TYPE solution_status DROP VALUE IF EXISTS 'PROJECT_GENERATION'")
    op.execute("ALTER TYPE solution_status DROP VALUE IF EXISTS 'VALIDATION_WAITING'")
    op.execute("ALTER TYPE solution_status DROP VALUE IF EXISTS 'CRITERIA_GRADING'")
    # ### end Alembic commands ###
